// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"2D_Cat_BeautifulSunshineFilter","status":true,"description":"v1.0 为游戏添加绮丽的日光效果滤镜。","parameters":{"beautifulSunshineEnabled":"true","godrayGain":"0.3","godrayLacunarity":"2.5","godrayAlpha":"1","godrayAngle":"30","godragSpeed":"5","advancedBloomBrightness":"0.9","advancedBloomThreshold":"1","advancedBloomBloomScale":"0.6","advancedBloomBlur":"8","advancedBloomQuality":"8"}},
{"name":"2D_Cat_PixelGameFilter","status":true,"description":"v1.1 为游戏添加像素化滤镜，并为游戏角色添加轮廓线。","parameters":{"pixelGameEnabled":"false","pixelateSize":"3","outlineColor":"#ffffff","outlineThickness":"4","outlinePlayerEnabled":"true"}},
{"name":"2D_Cat_BodyShakeMove","status":true,"description":"v1.0 角色移动时添加晃动身体的效果。","parameters":{"enableOnlyDash":"false"}},
{"name":"2D_Cat_FreestyleMsgText","status":true,"description":"v1.0 自由设定对话框文字式样，包括颜色、渐变色、加粗、倾斜、轮廓、阴影、辉光等效果。","parameters":{}},
{"name":"WeatherOnBattle","status":true,"description":"display weather not only map but also battle","parameters":{}},
{"name":"TorigoyaMZ_Achievement2","status":true,"description":"成就系统 (v.1.4.0)","parameters":{"base":"","baseAchievementData":"[\"{\\\"key\\\":\\\"结局一\\\",\\\"title\\\":\\\"结局一：还没开始就结束了\\\",\\\"description\\\":\\\"懦弱者，无法在波涛中存活。\\\",\\\"icon\\\":\\\"0\\\",\\\"hint\\\":\\\"\\\",\\\"isSecret\\\":\\\"false\\\",\\\"note\\\":\\\"\\\"}\"]","baseSaveSlot":"achievement","popup":"","popupEnable":"true","popupPosition":"leftUp","popupTopY":"10","popupAnimationType":"tween","popupWait":"1.25","popupWidth":"300","popupPadding":"10","popupTitleFontSize":"20","popupTitleColor":"1","popupMessage":"成就已激活","popupMessageFontSize":"16","popupSound":"{\"soundName\":\"Saint5\",\"soundVolume\":\"90\"}","popupWindowImage":"Window","popupOpacity":"-1","titleMenu":"","titleMenuUseInTitle":"true","titleMenuUseInMenu":"true","titleMenuText":"成就","achievementMenu":"","achievementMenuHiddenTitle":"？？？？？","achievementMenuHiddenIcon":"0","advanced":"","advancedFontFace":"","advancedOverwritable":"false"}},
{"name":"TorigoyaMZ_Achievement2_AddonCategory","status":true,"description":"成就附加插件: 类别设定 (v.1.1.1)","parameters":{"base":"","categories":"[\"{\\\"name\\\":\\\"结局\\\",\\\"prefix\\\":\\\"结局\\\"}\"]","position":"top","maxCols":"4"}},
{"name":"JP_battle_hp","status":true,"description":"V1.0 战斗场景显示战斗双方的血条V1.0.1 MZ版本","parameters":{"----敌人血条设置----":"","enemy_hp":"true","enemy_hp_x":"0","enemy_hp_y":"0","----队友血条设置----":"","player_hp":"true","player_hp_x":"0","player_hp_y":"0"}},
{"name":"XdRs_BubbleDialog","status":true,"description":"气泡对话框。","parameters":{}},
{"name":"AltSaveScreen","status":true,"description":"Alternative save/load screen layout.","parameters":{}}
];
